name: Get daedalus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: get file and push
        run: |
          wget https://github.com/DaedalusX64/daedalus/releases/download/1.1.8/DaedalusX64_1_1_8.zip
          git config --global user.email "Boss-1s[BOT]@users.noreply.gihub.com"
          git config --global user.name "Boss-1s[BOT]"
          bash push.sh
