name: code-server

on:
  workflow_dispatch:
    inputs:
      time:
        type: number
        default: 1
        required: true
        description: time to run server in mins

jobs:
  debug-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Test Official VS Code Tunnel
      run: |
        # Download the official VS Code binary
        curl -Lk 'https://visualstudio.com' --output vscode_cli.tar.gz
        tar -xf vscode_cli.tar.gz

        # Start the tunnel and keep it open for your 1-minute test window
        timeout ${{inputs.time}}m ./code tunnel --accept-server-license-terms || true
        
