name: Get any audio from youtube videos
description: Use youtube-to-audio to get audio from a yt video

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Link to run yt-dlp on.'
        type: string
        required: true
      format:
        description: 'Format to download in.'
        default: 'mp3'
        type: choice
        options:
          - mp3
          - m4a
          - wav
          - ogg
          - aac
          - flac
          - opus
      oname:
        description: 'Name of audio to be extracted. (Single videos only)'
        type: string
      pname:
        description: 'Folder name of audio to be extracted. (Playlists only)'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download Dependancies
        run: |
          pip install -U youtube-to-audio FFmpeg
      - name: get audio and push
        run: |
          youtube-to-audio --url ${{inputs.link}} --format ${{inputs.format}} --output_name ${{inputs.oname}} --playlist_name ${{inputs.pname}}
          git config --global user.email "Boss-1s[BOT]@users.noreply.gihub.com"
          git config --global user.name "Boss-1s[BOT]"
          bash push.sh
